version: 2
updates:
- package-ecosystem: docker
  cooldown:
    default-days: 4
  directories:
    - "/"
    - "/docker"
  schedule:
    interval: daily
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-major"]
  open-pull-requests-limit: 10

- package-ecosystem: devcontainers
  directory: "/"
  cooldown:
    default-days: 4
  schedule:
    interval: daily
  open-pull-requests-limit: 10

- package-ecosystem: pip
  directory: "/"
  cooldown:
    default-days: 4
    exclude:
      - ccxt
  schedule:
    interval: weekly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 15
  target-branch: develop
  groups:
    types:
      patterns:
        - "types-*"
    pytest:
      patterns:
        - "pytest*"
    mkdocs:
      patterns:
        - "mkdocs*"
    scipy:
      patterns:
        - "scipy"
        - "scipy-stubs"

- package-ecosystem: "github-actions"
  directory: "/"
  cooldown:
    default-days: 4
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
  target-branch: develop
